angle : [60., 90., 120.]            #incoming angle (°)
u_d : [5., 10., 15., 20., 25., 30.] #control velocity (kn)
rlw : [2.]                          #right lane width (nm)
llw : [2.]                          #left lane width (nm)
rld : [.1]                          #right lane density of obstacles (1/hm²)
lld : [.1]                          #left lane density of obstacles (1/hm²)
ld : [1.]                           #distance between lanes (nm)