angle : [60., 90., 120.]            #incoming angle (in degrees)
u_d : [5., 10., 15., 20., 25., 30.] #control velocity (in knots)
rld : [.00005]                         #right lane obstacle density (in 1/m²)
lld : [.00005]                         #left lane obstacle density (in 1/m²)
llw : [2.]                          #right lane width (in nautical miles)
rlw : [2.]                          #left lane width (in nautical miles)
ld : [1.]                           #distance between lanes (in nautical miles)