
# mapfile: mozambique.yaml #facultatif

# Simulation parameters
use_sim_time: false
trigger_shutdown: 1
coast_margin: 10

# Environment parameters
F_current: 0.0
direction_current: 0.0 #in deg
F_wind: 0.0
direction_wind: 0.0 #in deg
there_are_waves: false

asv:
  heading: 0.0
  u_d: [1,2,3,4,5,6,8,10,15] #m.s-1
  t_sim: 60

obstacles:
  ship1:
    prior: [none]
    size: [8.0] #radius in meters
    heading: [180]
    u_d: [1,2,3,4,5,6,8,10,15] #m.s-1
    t_collision: 40
    d_detection: [500.0]
    dcpa: [0.0]
