  # Fx_current: 0.0
  # Fy_current: 0.0

  # sigma_x:  25000.8064
  # omega0_x: 0.8
  # lambda_x: 0.12
  # gain_x:   1.0
  #
  # sigma_y:  25000.3874
  # omega0_y: 0.9
  # lambda_y: 0.15
  # gain_y:   1.0
  #
  # sigma_psi:  43500.2344
  # omega0_psi: 0.8
  # lambda_psi: 0.10
  # gain_psi:   1.0

  mapfile: mozambique.yaml #facultatif

  trajectories: [[[580.0, 110.0, 0., 0., 0., 0.], [1200.0, 110.0]],
                 [[760.0, 850.0, -1.56, 0., 0., 0.], [760.0, 0.0]]]

  # u_d:

  use_sim_time: false
  trigger_shutdown: 0
  coast_margin: 10
